### ISSUE TITLE
link to run script in the minimal example?

### ISSUE THREAD

**Issue by kendonB** [wlandau/targets-minimal#2]
## Prework

* [x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targets-minimal/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to `targets`' [contributing guidelines](https://github.com/wlandau/targets-minimal/blob/master/CONTRIBUTING.md).

## Description

Just trying to get started with targets locally and I didn't see an example `run.R` or `run.sh` on https://github.com/wlandau/targets-minimal right away - I now see them in the files above. Maybe put links to them in point 2 here: https://github.com/wlandau/targets-minimal#how-to-run?

**Comment by kendonB** [comment]
Might even be better to spell out in point 1. here https://github.com/wlandau/targets-minimal#how-to-run which files to copy to your local working directory?

**Comment by wlandau** [comment]
Good points. I added some more guidance and links. For running locally, it's best to just clone or download the whole thing.
