### ISSUE TITLE
literate programming link is broken

### ISSUE THREAD

**Issue by kendonB** [wlandau/targets-minimal#3]
## Prework

* [x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targets-minimal/blob/master/CODE_OF_CONDUCT.md).
* [x] I understand and agree to this repository's [contributing guidelines](https://github.com/wlandau/targets-minimal/blob/master/CONTRIBUTING.md).
* [x] I am reasonably sure this is a genuine bug in this repository's code and most likely not a user error. (If you run into an error and do not know the cause, please submit a "Trouble" issue instead.)

## Description

The link under "literate programming chapter of the manual": `https://wlandau.github.io/literate.html` is broken on the front page of this repo.

**Comment by wlandau** [comment]
Thanks, now fixed.
