### ISSUE TITLE
Repository tag typo: high-perofrmance-computing

### ISSUE THREAD

**Issue by KaiAragaki** [wlandau/targets-minimal#7]
## Prework

* [x] I understand and agree to this repository's [code of conduct](https://github.com/wlandau/targets-minimal/blob/main/CODE_OF_CONDUCT.md).
* [x] I understand and agree to this repository's [contributing guidelines](https://github.com/wlandau/targets-minimal/blob/main/CONTRIBUTING.md).

## Description

Repository tag is "high-perofrmance-computing", should likely be "high-performance-computing"

Thanks for all you do!

**Comment by wlandau** [comment]
Thanks @KaiAragaki, now fixed.
